"""Initial migration

Revision ID: 46ba27ff3c2a
Revises: 5af1f326b41f
Create Date: 2024-10-13 12:05:06.228796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ba27ff3c2a'
down_revision = '5af1f326b41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)  # Permitir NULL inicialmente

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)  # Mantener como NULL en la reversión

    # ### end Alembic commands ###

